### ISSUE TITLE
The method 'getisdeletedfromstage' does not exist on 'CalendarEvent'

### ISSUE THREAD

**Issue by silverstripe-elliot** [webbuilders-group/silverstripe-gridfield-calendar-view#2]
Hello! Thanks for creating this module - the CMS has needed something like it for a long time. Nice work!

I was evaluating your module and received this error on 3.4 and 3.5 when trying to display the calendar view. If I define that method on my DataObject and return true, the calendar renders as expected.

Here's my code:
```

class CalendarEvent extends DataObject {
    private static $db = [
      'Title'=>'Varchar(255)',
      'Summary'=>'Varchar(1000)',
      'IsAllDay'=>'Boolean',
      'Start'=>'SS_Datetime',
      'End'=>'SS_Datetime'
    ];

    private static $has_one = [
      'Parent' => 'EventPage'
    ];

class EventPage extends Page {
    private static $has_many = [
        'Events' => 'CalendarEvent'
    ];

	public function getCMSFields() {
		$fields = parent::getCMSFields();
		$eventCalendarGridField = new GridField('Events', 'Events', $this->Events(), GridFieldConfig_RecordEditor::create(10));
		$eventCalendarGridField->getConfig()->addComponent(new GridFieldCalendarView(
			'Start', //This must be the name of the field in the model not a getter method
            'End'
		));

        $fields->addFieldToTab("Root.Main", $eventCalendarGridField, "Content");

		return $fields;
	}
}
```

The issue disappears when I add the following code to CalendarEvent:
```
    public function getisdeletedfromstage() {
      return true;
    }
```

I haven't had a chance to dig into the module code to see where the issue lies, but hopefully this info helps anyone else who runs into the problem!

**Comment by UndefinedOffset** [comment]
Right it's probably something we had as a hook in the project we originally built this for before we separated out to it's own module. Good catch I'll look into it Monday and let you know when we have a fix :)

**Comment by UndefinedOffset** [comment]
I think you could comment out this line https://github.com/webbuilders-group/silverstripe-gridfield-calendar-view/blob/master/code/forms/gridfield/GridFieldCalendarView.php#L245 as a temporary fix until I have a chance to correct it properly.
